name: Publish GitHub Page
description: Publish a GitHub Page Action
author: Rizart Dokollari <r.dokollari@gmail.com>

branding:
  icon: layers
  color: gray-dark

inputs:
  directory:
    description: The directory to publish.
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.directory }}
