name: build-status
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: ./
        with:
          directory: build
          github-token: ${{ github.token }}
